### ISSUE TITLE
issue with rundsent file:same power with all stats files

### ISSUE THREAD

**Issue by Superstite** [Davxx/gem5_Garnet2.0_extensions#1]
Hi, 
When I run rundsent file with different stats files, it always produces the same output power of routers each time. 
Can you help me resolve it?

**Comment by Davxx** [comment]
Hello,

rundsent calls util/on-chip-network-power-area-2.0.py
The 2nd and 3rd parameters of that script default to: <simulation
directory>/router.cfg and <simulation directory>/electrical-link.cfg
You could check those config files to see if they are correct for your
simulation results.
You could also tweak line 121 of util/on-chip-network-power-area-2.0.py to
return custom values for (core_area, cpu_model_name, cpu_model_die_size,
model_approx_core_size)
Try print(core_area, cpu_model_name, cpu_model_die_size,
model_approx_core_size) first to see what values are used for your
simulation dir.

Regards,
David

**Comment by Davxx** [comment]
You can also edit configs/topologies/TopologyToDSENT.py to modify the
generated DSENT router.cfg and electrical-link.cfg files.
